=== FlooferLand/wsearch/artworks/_schemas/metadata.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ArtworkMetadata",
  "type": "object",
  "properties": {
    "coords": {
      "$ref": "#/$defs/ArtworkGlobalCoords"
    },
    "credits": {
      "$ref": "#/$defs/ArtworkCredits"
    },
    "image": {
      "$ref": "#/$defs/ArtworkImage"
    },
    "license": {
      "type": [
        "string",
        "null"
      ]
    },
    "name": {
      "type": "string"
    },
    "region": {
      "$ref": "#/$defs/GeographicalRegion"
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "credits",
    "coords",
    "image",
    "region"
  ],
  "$defs": {
    "ArtworkCredits": {
      "type": "object",
      "properties": {
        "artists": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          }
        },
        "maintainers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "maintainers"
      ]
    },
    "ArtworkGlobalCoords": {
      "type": "object",
      "properties": {
        "link": {
          "type": "string"
        },
        "top_left": {
          "$ref": "#/$defs/PixelCoords"
        }
      },
      "required": [
        "link",
        "top_left"
      ]
    },
    "ArtworkImage": {
      "type": "object",
      "properties": {
        "coords": {
          "$ref": "#/$defs/PixelCoords"
        },
        "png": {
          "type": "string"
        },
        "tile": {
          "$ref": "#/$defs/PixelCoords"
        }
      },
      "required": [
        "tile",
        "coords",
        "png"
      ]
    },
    "GeographicalRegion": {
      "type": "object",
      "properties": {
        "country": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "country",
        "state"
      ]
    },
    "PixelCoords": {
      "type": "array",
      "maxItems": 2,
      "minItems": 2,
      "prefixItems": [
        {
          "type": "integer",
          "format": "int32"
        },
        {
          "type": "integer",
          "format": "int32"
        }
      ]
    }
  }
}

=== FlooferLand/wsearch/artworks/scav_creature/metadata.json
{
    "name": "Scav Prototype creature",
    "credits": {
        "maintainers": [
            "TrueChaos #4309268",
            "FlooferLand (RO) #5674026 (@flooferland)"
        ],
        "artists": ["TrueChaos #4309268"],
        "additional": "Original design from Scav Prototype"
    },
    "region": { "country": "ro", "state": "Arad" },
    "coords": {
        "link": "https://wplace.live/?lat=46.17830923535645&lng=21.372275059277328&zoom=16.207932134442082",
        "top_left": [1584, 3137]
    },
    "image": {
        "tile": [1145, 727],
        "coords": [584, 137],
        "png": "scav_creature.png"
    }
}
