=== FlooferLand/wsearch/artworks/_schemas/overlay.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "OverlayPro",
  "description": "Overlay file for Overlay Pro",
  "type": "object",
  "properties": {
    "imageUrl": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "offsetX": {
      "type": "integer",
      "format": "int32"
    },
    "offsetY": {
      "type": "integer",
      "format": "int32"
    },
    "opacity": {
      "type": "number",
      "format": "float"
    },
    "pixelUrl": {
      "type": "string"
    },
    "version": {
      "type": "integer",
      "format": "int32"
    }
  },
  "required": [
    "version",
    "name",
    "imageUrl",
    "pixelUrl",
    "offsetX",
    "offsetY",
    "opacity"
  ]
}

=== FlooferLand/wsearch/artworks/random_logo_area/overlay.json
{
    "version": 1,
    "name": "Random logo area",
    "imageUrl": "https://github.com/FlooferLand/wplace-art/blob/main/random_logo_area/random_logo_area.png?raw=true",
    "pixelUrl": "https://backend.wplace.live/s0/pixel/1145/727?x=465&y=128",
    "offsetX": 0,
    "offsetY": 0,
    "opacity": 0.7
}
